kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: default
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-cfg
  labels:
    app: traefik
data:
  traefik-acme.toml: |
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
    email = "lucas@luxaslabs.com"
    storageFile = "/etc/traefik-certs/acme.json"
    onDemand = true
    onHostRule = true
    caServer = "https://acme-v01.api.letsencrypt.org/directory"
    entryPoint = "https"

    # Enable the kubernetes integration
    [kubernetes]

    [web]
    address = ":8080"

    [web.statistics]

    [web.metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: traefik-ingress-controller
  name: traefik-ingress-controller
spec:
  selector:
    matchLabels:
      app: traefik-ingress-controller
  template:
    metadata:
      labels:
        app: traefik-ingress-controller
    spec:
      nodeSelector:
        ingress-controller: "true"
      serviceAccountName: traefik-ingress-controller
      containers:
      - image: traefik:v1.3-alpine
        name: traefik-ingress-controller
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: web
          containerPort: 8080
        args:
        - --configfile=/etc/traefik/traefik-acme.toml
        volumeMounts:
        - name: traefik-cfg
          mountPath: /etc/traefik/
        - name: traefik-certs
          mountPath: /etc/traefik-certs/
      volumes:
      - name: traefik-cfg
        configMap:
          name: traefik-cfg
      - name: traefik-certs
        hostPath:
          path: /etc/traefik/certs/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik-ingress-controller
  name: traefik-ingress-controller
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: traefik-ingress-controller
